export const colors = {
  background: "#eef3f9",
  foreground: "#0f172a",
  card: "#ffffff",
  muted: "#e2eaf4",
  mutedForeground: "rgba(15, 23, 42, 0.58)",
  primary: "#0f172a",
  accent: "#ea7a53",
  /** Home “monthly recurring” card — distinct from CTA orange */
  balance: "#355c7d",
  border: "rgba(15, 23, 42, 0.1)",
  success: "#16a34a",
  destructive: "#dc2626",
  subscription: "#8fd1bd",
};

export const spacing = {
  0: 0,
  1: 4,
  2: 8,
  3: 12,
  4: 16,
  5: 20,
  6: 24,
  7: 28,
  8: 32,
  9: 36,
  10: 40,
  11: 44,
  12: 48,
  14: 56,
  16: 64,
  18: 72,
  20: 80,
  24: 96,
  30: 120,
};

// Optional font family tokens (once you configure fonts in Expo)
export const fonts = {
  sans: "sans-regular",
  sansLight: "sans-light",
  sansMedium: "sans-medium",
  sansSemibold: "sans-semibold",
  sansBold: "sans-bold",
  sansExtrabold: "sans-extrabold",
};

export const semanticClasses = {
  "tabs-icon": "size-12 items-center justify-center",
  "tabs-pill": "size-12 items-center justify-center rounded-full bg-transparent",
  "tabs-active": "bg-accent",
  "tabs-glyph": "size-6",
  "home-header": "mb-2.5 flex-row items-center justify-between",
  "home-user": "flex-row items-center",
  "home-avatar": "size-16 rounded-full",
  "home-user-name": "ml-4 text-2xl font-sans-bold text-primary",
  "home-add-icon": "size-12",
  "home-balance-card": "my-2.5 min-h-50 gap-3 rounded-3xl bg-balance p-6",
  "home-balance-label": "text-lg font-sans-semibold text-white/85",
  "home-balance-stack": "gap-2",
  "home-balance-amount": "text-3xl font-sans-extrabold text-white",
  "home-balance-meta": "text-[15px] font-sans-medium leading-snug text-white/95",
  "list-head": "my-5 flex-row items-center justify-between",
  "list-title": "text-2xl font-sans-bold text-primary",
  "list-action": "rounded-full border border-black/20 px-4 py-1",
  "list-action-text": "text-sm font-sans-semibold text-primary",
  "upcoming-card": "mr-4 w-44 rounded-2xl border border-black/10 bg-background p-4",
  "upcoming-row": "flex-row items-center gap-3",
  "upcoming-icon": "size-14",
  "upcoming-price": "text-lg font-sans-bold text-primary",
  "upcoming-meta": "text-sm font-sans-semibold text-muted-foreground",
  "upcoming-name": "mt-2 text-lg font-sans-bold text-primary",
  "sub-card": "rounded-2xl border border-border p-4",
  "sub-card-expanded": "bg-subscription",
  "sub-head": "flex-row items-center py-2",
  "sub-main": "min-w-0 flex-1 flex-row items-center gap-3",
  "sub-icon": "size-16 rounded-lg",
  "sub-copy": "min-w-0 flex-1",
  "sub-title": "mb-1 text-lg font-sans-bold text-primary",
  "sub-meta": "text-sm font-sans-semibold text-muted-foreground",
  "sub-price-box": "ml-3 shrink-0 items-end",
  "sub-price": "mb-1 text-lg font-sans-bold text-primary",
  "sub-billing": "text-sm font-sans-medium text-muted-foreground",
  "sub-body": "mt-6 gap-4",
  "sub-details": "gap-6",
  "sub-row": "flex-row items-center justify-between gap-3",
  "sub-row-copy": "min-w-0 flex-1 flex-row items-center gap-2",
  "sub-label": "shrink-0 text-base font-sans-medium text-muted-foreground",
  "sub-value": "flex-1 font-sans-bold text-primary",
  "sub-cancel": "mt-2 items-center rounded-full bg-primary py-4",
  "sub-cancel-disabled": "bg-primary/35",
  "sub-cancel-text": "font-sans-bold text-background",
  "home-empty-state": "py-4 text-sm font-sans-medium text-black/60",
  "auth-safe-area": "flex-1 bg-background",
  "auth-screen": "flex-1 bg-background",
  "auth-scroll": "flex-1",
  "auth-content": "grow px-5 pb-10 pt-8",
  "auth-brand-block": "mt-2 items-center",
  "auth-logo-wrap": "mb-7 flex-row items-center gap-3",
  "auth-logo-mark": "relative size-14 items-center justify-center rounded-2xl bg-accent",
  "auth-logo-mark-text": "text-2xl font-sans-extrabold text-background",
  "auth-wordmark": "text-3xl font-sans-extrabold text-primary",
  "auth-wordmark-sub": "-mt-1 text-xs font-sans-semibold uppercase tracking-[1px] text-muted-foreground",
  "auth-title": "text-3xl font-sans-bold text-primary",
  "auth-subtitle": "mt-2 max-w-[320px] text-center text-base font-sans-medium text-muted-foreground",
  "auth-card": "mt-8 rounded-3xl border border-border bg-card p-5",
  "auth-form": "gap-4",
  "auth-field": "gap-2",
  "auth-label": "text-sm font-sans-semibold text-primary",
  "auth-input": "rounded-2xl border border-border bg-background px-4 py-4 text-base font-sans-medium text-primary",
  "auth-input-error": "border-destructive",
  "auth-error": "text-xs font-sans-medium text-destructive",
  "auth-helper": "text-sm font-sans-medium text-muted-foreground",
  "auth-button": "mt-1 items-center rounded-2xl bg-accent py-4",
  "auth-button-disabled": "bg-accent/45",
  "auth-button-text": "text-base font-sans-bold text-primary",
  "auth-secondary-button": "items-center rounded-2xl border border-accent/30 bg-accent/10 py-3",
  "auth-secondary-button-text": "text-sm font-sans-semibold text-accent",
  "auth-divider-row": "my-4 flex-row items-center gap-3",
  "auth-divider-line": "h-px flex-1 bg-border",
  "auth-divider-text": "text-[11px] font-sans-semibold uppercase tracking-[1px] text-muted-foreground",
  "auth-link-row": "mt-5 flex-row items-center justify-center gap-1",
  "auth-link-copy": "text-sm font-sans-medium text-muted-foreground",
  "auth-link": "text-sm font-sans-bold text-accent",
  "modal-overlay": "flex-1 bg-black/50",
  "modal-container": "mt-auto max-h-[85%] rounded-t-3xl bg-background",
  "modal-header": "flex-row items-center justify-between border-b border-border px-5 py-4",
  "modal-title": "text-xl font-sans-bold text-primary",
  "modal-close": "size-8 items-center justify-center rounded-full bg-muted",
  "modal-close-text": "text-lg font-sans-bold text-primary",
  "modal-body": "gap-5 p-5",
  "picker-row": "flex-row gap-3",
  "picker-option": "flex-1 items-center rounded-2xl border border-border bg-background py-3",
  "picker-option-active": "border-accent bg-accent/10",
  "picker-option-text": "text-sm font-sans-semibold text-muted-foreground",
  "picker-option-text-active": "text-accent",
  "category-scroll": "flex-row flex-wrap gap-2",
  "category-chip": "rounded-full border border-border bg-background px-4 py-2",
  "category-chip-active": "border-accent bg-accent/10",
  "category-chip-text": "text-sm font-sans-semibold text-muted-foreground",
  "category-chip-text-active": "text-accent",
};

